### ISSUE TITLE
Does this work? Want to use with a Proliphix Thermostat.

### ISSUE THREAD

**Issue by psmith3** [PJCzx/homebridge-thermostat#1]
I have a a Proliphix Thermostat that has an http API and would like to see if this will work with it. Do you have any documentation on this project?

**Comment by init4** [comment]
It seems pretty broken/incomplete, sending it even basic commands causes homebridge to crash:

---

4/10/2016, 4:11:19 PM] [Bedroom Thermostat] getCoolingThresholdTemperature
[4/10/2016, 4:11:19 PM] [Bedroom Thermostat] getHeatingThresholdTemperature
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at Object.Thermostat.getHeatingThresholdTemperature (/usr/local/lib/node_modules/homebridge-thermostat/index.js:100:3)
    at emitTwo (events.js:105:20)
    at emit (events.js:185:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:603:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:567:8)
    at emitThree (events.js:110:13)
    at HAPServer.emit (events.js:188:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:914:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:201:39)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)

##     at process._tickCallback (node.js:407:11)

**Comment by PJCzx** [comment]
Hi,

This was the basic commands based on Documentation. 

I will have a look but I'm not maintaining it since a while. Feel free to make pull request.

Best

Pierre-Julien Cazaux,
Envoyé depuis mon mobile.

**Comment by PJCzx** [comment]
I just updated the code, it was not broken so this was supposed to work on your machine. In any case, some basci commands was missing. I just added it. please have a look at it and don't hesitate to come back to me if you need any update.
