### ISSUE TITLE
getting error message

### ISSUE THREAD

**Issue by roberkane212** [PJCzx/homebridge-thermostat#44]
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at Thermostat.<anonymous> (/usr/local/lib/node_modules/homebridge-thermostat/index.js:93:27)
    at Request._callback (/usr/local/lib/node_modules/homebridge-thermostat/index.js:65:15)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-thermostat/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-thermostat/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-thermostat/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by phenotypic** [comment]
The JSON your API is returning when you request `/status` is improperly formatted so the plugin can't parse it, throwing this error. Would you be able to give an example of the JSON your API is trying to return?

**Comment by roberkane212** [comment]
"accessory": "Thermostat",
			"name": "Thermostat",
			"apiroute": "https://www.mytotalconnectcomfort.com/portal/"

**Comment by roberkane212** [comment]
is this wrong? should i input username and password?

**Comment by phenotypic** [comment]
That looks to be your `config.json`. Please show what your API returns when you request `/status`. It should follow [this](https://github.com/PJCzx/homebridge-thermostat#api-interfacing) specification.

**Comment by roberkane212** [comment]
It’s not I’m getting error message, should I use ip of my thermostat instead
